In [28]:
import pandas as pd
import numpy as np
import logging

import pymysql
from datetime import datetime

In [31]:
### At first we use the PyMysql engine to extract data and load the data directly to file

In [33]:
connection_config = {
    "host":"localhost",
    "user":"root",
    "password":"RootRender90",
    "database":"erpnext_db",
    "port":3306
}

with pymysql.connect(**connection_config) as connection:
    query = """ SELECT 
                    name, 
                    customer, 
                    customer_name, 
                    posting_date, 
                    due_date, 
                    base_grand_total FROM `tabSales Invoice` WHERE docstatus = 1 
                    AND YEAR(posting_date) = 2026"""
    df = pd.read_sql(query, connection)
    today_date = datetime.strftime(datetime.today(),"%Y-%m-%d")
    df.to_parquet(f"data/sales_invoice_{today_date}.parquet")

/tmp/ipykernel_34183/2298813164.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection)

### Now we move towards extracting the data using SQLAlchemy

SQLAlchemy helps us manage database connections, create an abstraction layer, handles lazy loading and relationship management.

In [36]:
from sqlalchemy import create_engine, text
from sqlalchemy.pool import QueuePool

In [50]:
## database connection manager / factory to handle connection to a database i.e mysql, oracle, postgresql

## create engine with connection pooling
engine = create_engine(
    "mysql+pymysql://root:RootRender90@localhost/erpnext_db",
    pool_size=10, ## Number of connections to keep in the pool
    max_overflow = 10, ## extra pools to add if pool is exhausted
    pool_pre_ping=True, ## Check connection validity
    echo=False ## do not see SQL logs
)

query = text("""SELECT 
                    name, 
                    customer, 
                    customer_name, 
                    posting_date, 
                    due_date, 
                    base_grand_total FROM `tabSales Invoice` WHERE docstatus = 1 
                    AND YEAR(posting_date) = 2026 """)

with engine.connect() as connection:
    df_a = pd.read_sql(query, connection)

df_a.head()

,name,customer,customer_name,posting_date,due_date,base_grand_total
0,ACC-SINV-2026-00001,NMC-00204,MAZIMA BUGAGGA,2026-01-01,2026-01-10,43200.0
1,ACC-SINV-2026-00002,CUST-2025-00119,SPENZA LIMITED,2026-01-01,2026-01-29,114000.0
2,ACC-SINV-2026-00003,NMC-00195,REDLARK GENERAL HOLDINGS LTD,2026-01-01,2025-12-31,55750.0
3,ACC-SINV-2026-00004,CUST-2025-00200,ANDYVAN FREIGHT LOGISTICS,2026-01-01,2026-01-14,40800.0
4,ACC-SINV-2026-00005,NMC-00240,GAJANAN BUILDING SOLUTIONS LIMITED,2026-01-01,2026-03-02,99180.0

In [53]:

mysql_engine = create_engine("mysql+pymysql://root:RootRender90@localhost/erpnext_db",
                           pool_size=10,
                           pool_pre_ping=True,
                           max_overflow=5)

def extract_data_from_erp():
    query = text(""" SELECT 
                        name, 
                        supplier, 
                        supplier_name, 
                        posting_date, 
                        due_date, base_grand_total,
                        base_net_total FROM `tabPurchase Invoice` WHERE docstatus = 1 
                        AND is_return = 0 ORDER BY posting_date DESC""")

    with mysql_engine.connect() as connection:
        df = pd.read_sql(query, connection)
    return df

In [54]:
extract_data_from_erp()

,name,supplier,supplier_name,posting_date,due_date,base_grand_total,base_net_total
0,ACC-PINV-2026-01236,SUP-2025-00046,GIANTOS SECURITY SERVICES,2026-06-01,2026-06-01,111360.0,96000.0
1,ACC-PINV-2026-01218,SUP-2025-00110,STEPPING STONE TRANSPORTERS ENT LTD,2026-05-26,2026-06-09,76560.0,66000.0
2,ACC-PINV-2026-01216,SUP-2025-00110,STEPPING STONE TRANSPORTERS ENT LTD,2026-05-25,2026-06-08,76560.0,66000.0
3,ACC-PINV-2026-01217,SUP-2025-00110,STEPPING STONE TRANSPORTERS ENT LTD,2026-05-25,2026-06-08,76560.0,66000.0
4,ACC-PINV-2026-01222,SUP-2025-00198,VIVO ENERGY KENYA LIMITED,2026-05-25,2026-06-24,2328588.0,2156100.0
...,...,...,...,...,...,...,...
2314,ACC-PINV-2025-00910-1,SUP-2025-00017,BAPS HARDWARE LTD,2025-08-01,2025-08-31,459717.0,459717.0
2315,ACC-PINV-2025-00915-1,SUP-2025-00115,TIGER PACKAGING,2025-08-01,2025-09-30,51040.0,51040.0
2316,ACC-PINV-2025-01137-1,SUP-2025-00217,OMTECH ELECTRICAL REWINDERS AND GENERAL SERVICES,2025-08-01,2025-08-01,348580.0,348580.0
2317,ACC-PINV-2025-00378,SUP-2025-00162,FRANK & GEOFFREY CARGO LIMITED,2025-07-14,2025-08-13,57934.0,57934.0
2318,ACC-PINV-2026-00875,SUP-2025-00179,SHANDONG INVECH MINING TECHNOLOGY CO LIMITED,2024-09-30,2024-09-30,13226733.0,12672936.0

In [ ]:
### Parametized query to get data using parameters

def get_invoice_by_customer(customer_id):
    query = text("""
                    SELECT si.name,
                           si.customer_name,
                           si.posting_date, 
                           si.due_date,
                           si.payment_terms_template,
                           si.base_grand_total,
                           si.outstanding_amount,
                           si.status
                    FROM `tabSales Invoice` AS si 
                    WHERE si.customer =:customer_id
                    AND si.docstatus = 1
                    ORDER BY si.posting_date DESC
                """)

    with mysql_engine.connect() as connection:
        result = connection.execute(query, {"customer_id":customer_id})
        df = pd.DataFrame(result.fetcall