In [28]:
import pandas as pd
import numpy as np
import logging

import pymysql
from datetime import datetime

In [31]:
### At first we use the PyMysql engine to extract data and load the data directly to file

In [33]:
connection_config = {
    "host":"localhost",
    "user":"root",
    "password":"RootRender90",
    "database":"erpnext_db",
    "port":3306
}

with pymysql.connect(**connection_config) as connection:
    query = """ SELECT 
                    name, 
                    customer, 
                    customer_name, 
                    posting_date, 
                    due_date, 
                    base_grand_total FROM `tabSales Invoice` WHERE docstatus = 1 
                    AND YEAR(posting_date) = 2026"""
    df = pd.read_sql(query, connection)
    today_date = datetime.strftime(datetime.today(),"%Y-%m-%d")
    df.to_parquet(f"data/sales_invoice_{today_date}.parquet")

/tmp/ipykernel_34183/2298813164.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection)

### Now we move towards extracting the data using SQLAlchemy

SQLAlchemy helps us manage database connections, create an abstraction layer, handles lazy loading and relationship management.

In [36]:
from sqlalchemy import create_engine, text
from sqlalchemy.pool import QueuePool

In [50]:
## database connection manager / factory to handle connection to a database i.e mysql, oracle, postgresql

## create engine with connection pooling
engine = create_engine(
    "mysql+pymysql://root:RootRender90@localhost/erpnext_db",
    pool_size=10, ## Number of connections to keep in the pool
    max_overflow = 10, ## extra pools to add if pool is exhausted
    pool_pre_ping=True, ## Check connection validity
    echo=False ## do not see SQL logs
)

query = text("""SELECT 
                    name, 
                    customer, 
                    customer_name, 
                    posting_date, 
                    due_date, 
                    base_grand_total FROM `tabSales Invoice` WHERE docstatus = 1 
                    AND YEAR(posting_date) = 2026 """)

with engine.connect() as connection:
    df_a = pd.read_sql(query, connection)

df_a.head()

,name,customer,customer_name,posting_date,due_date,base_grand_total
0,ACC-SINV-2026-00001,NMC-00204,MAZIMA BUGAGGA,2026-01-01,2026-01-10,43200.0
1,ACC-SINV-2026-00002,CUST-2025-00119,SPENZA LIMITED,2026-01-01,2026-01-29,114000.0
2,ACC-SINV-2026-00003,NMC-00195,REDLARK GENERAL HOLDINGS LTD,2026-01-01,2025-12-31,55750.0
3,ACC-SINV-2026-00004,CUST-2025-00200,ANDYVAN FREIGHT LOGISTICS,2026-01-01,2026-01-14,40800.0
4,ACC-SINV-2026-00005,NMC-00240,GAJANAN BUILDING SOLUTIONS LIMITED,2026-01-01,2026-03-02,99180.0

In [89]:

mysql_engine = create_engine("mysql+pymysql://root:RootRender90@localhost/erpnext_db",
                           pool_size=10,
                           pool_pre_ping=True,
                           max_overflow=5,
                            echo=False)

def extract_data_from_erp():
    query = text(""" SELECT 
                        name, 
                        supplier, 
                        supplier_name, 
                        posting_date, 
                        due_date, base_grand_total,
                        base_net_total FROM `tabPurchase Invoice` WHERE docstatus = 1 
                        AND is_return = 0 ORDER BY posting_date DESC""")

    with mysql_engine.connect() as connection:
        df = pd.read_sql(query, connection)
    return df

In [87]:
#extract_data_from_erp()

In [55]:
### Parametized query to get data using parameters

def get_invoice_by_customer(customer_id):
    query = text("""
                    SELECT si.name,
                           si.customer_name,
                           si.posting_date, 
                           si.due_date,
                           si.payment_terms_template,
                           si.base_grand_total,
                           si.outstanding_amount,
                           si.status
                    FROM `tabSales Invoice` AS si 
                    WHERE si.customer =:customer_id
                    AND si.docstatus = 1
                    ORDER BY si.posting_date DESC
                """)

    with mysql_engine.connect() as connection:
        
        result = connection.execute(query, {"customer_id":customer_id})
        
        df = pd.DataFrame(result.fetchall(), columns = result.keys())
    return df

In [86]:
res = get_invoice_by_customer("CUST-2025-00254")

2026-08-24 12:18:12,581 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2026-08-24 12:18:12,584 INFO sqlalchemy.engine.Engine
                    SELECT si.name,
                           si.customer_name,
                           si.posting_date,
                           si.due_date,
                           si.payment_terms_template,
                           si.base_grand_total,
                           si.outstanding_amount,
                           si.status
                    FROM `tabSales Invoice` AS si
                    WHERE si.customer =%(customer_id)s
                    AND si.docstatus = 1
                    ORDER BY si.posting_date DESC

INFO:sqlalchemy.engine.Engine:
                    SELECT si.name,
                           si.customer_name,
                           si.posting_date,
                           si.due_date,
                           si.payment_terms_template,
                           si.base_grand_total,
                           si.outstanding_amount,
                           si.status
                    FROM `tabSales Invoice` AS si
                    WHERE si.customer =%(customer_id)s
                    AND si.docstatus = 1
                    ORDER BY si.posting_date DESC

2026-08-24 12:18:12,588 INFO sqlalchemy.engine.Engine [generated in 0.00695s] {'customer_id': 'CUST-2025-00254'}

INFO:sqlalchemy.engine.Engine:[generated in 0.00695s] {'customer_id': 'CUST-2025-00254'}

2026-08-24 12:18:12,595 INFO sqlalchemy.engine.Engine ROLLBACK

INFO:sqlalchemy.engine.Engine:ROLLBACK

In [62]:
def individual_sales_report():
    query = text(""" 
                    SELECT 
                        si.name AS invoice_number,
                        si.posting_date,
                        si.customer,
                        si.customer_name,
                        st.sales_person,
                        si.due_date,
                        si.currency,
                        si.payment_terms_template,
                        sii.item_code,
                        sii.item_name, 
                        sii.rate,
                        sii.qty,
                        ROUND(si.base_grand_total,2) AS base_grand_total,
                        ROUND(si.outstanding_amount,2) AS outstanding_amount,
                        si.status
                    FROM `tabSales Invoice Item` AS sii 
                        INNER JOIN `tabSales Invoice` AS si ON sii.parent = si.name
                        LEFT JOIN `tabSales Team` AS st ON si.customer = st.parent
                    WHERE si.docstatus = 1 
                        AND si.is_opening = 0
                        AND si.is_return = 0
                        AND si.status NOT IN ('Credit Note Issued')
                    ORDER BY si.posting_date DESC
                    """)
    with mysql_engine.connect() as connection:
        df = pd.read_sql(query, connection)
        
    if not df.empty:
        df['amount_paid'] = df['base_grand_total'] -  df['outstanding_amount']

    return df

In [65]:
item_wise_sales = individual_sales_report()

In [ ]:
item_wise_sales.sort_values(by='amount_paid',ascending=False).query("status == 'Paid' ")

,invoice_number,posting_date,customer,customer_name,sales_person,due_date,currency,payment_terms_template,item_code,item_name,rate,qty,base_grand_total,outstanding_amount,status,amount_paid
11420,ACC-SINV-2025-01415-1,2025-08-01,NMC-00012,CRYSTAL ADHESIVES,Martha Nalonja,2025-10-30,KES,,None,Opening Invoice Item,6078168.0,1.0,6078168.0,0.0,Paid,6078168.0
11419,ACC-SINV-2025-01414-1,2025-08-01,NMC-00012,CRYSTAL ADHESIVES,Martha Nalonja,2025-10-30,KES,,None,Opening Invoice Item,5256134.0,1.0,5256134.0,0.0,Paid,5256134.0
11418,ACC-SINV-2025-01413-1,2025-08-01,NMC-00012,CRYSTAL ADHESIVES,Martha Nalonja,2025-10-30,KES,,None,Opening Invoice Item,4813930.4,1.0,4813930.4,0.0,Paid,4813930.4
11417,ACC-SINV-2025-01412-1,2025-08-01,NMC-00012,CRYSTAL ADHESIVES,Martha Nalonja,2025-10-30,KES,,None,Opening Invoice Item,4385832.4,1.0,4385832.4,0.0,Paid,4385832.4
11548,ACC-SINV-2025-02763-1,2025-08-01,CUST-2025-00254,KAKUZI,Martha Nalonja,2025-08-31,KES,,None,Opening Invoice Item,3901650.0,1.0,3901650.0,0.0,Paid,3901650.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7010,ACC-SINV-2025-04799,2025-12-02,NMC-00268,Aquacare Technologies ltd,George Oduor,2025-12-01,KES,Advance Payment,FG-0011,FEED LIME - 50KGS,250.0,2.0,500.0,0.0,Paid,500.0
412,ACC-SINV-2026-04857,2026-05-16,NMC-00414,TOP BAR COMPANY,Fiona Colly,2026-05-16,KES,Advance Payment,FG-0034,NEVCAL WHITE 20 - 50KGS,425.0,1.0,493.0,0.0,Paid,493.0
5072,ACC-SINV-2026-00729,2026-01-22,CUST-2025-00174,MARVEL PAINTS,George Oduor,2026-01-22,KES,Advance Payment,FG-0030,NEVCAL WHITE 15 - 50KGS,400.0,1.0,464.0,0.0,Paid,464.0
11279,ACC-SINV-2025-00643,2025-08-05,NMC-00145,BENARD KAAI,Gladys Wainaina,2025-08-05,KES,None,FG-0009,DOLO LIME - 50KGS,250.0,1.0,250.0,0.0,Paid,250.0
10354,ACC-SINV-2025-01738,2025-09-01,CUST-2025-00189,TIROSS MANUFACTURERS,George Oduor,2025-09-24,KES,30 Days Credit,FG-0034,NEVCAL WHITE 20 - 50KGS,0.0,7.0,0.0,0.0,Paid,0.0

### Extracting large databases / tables with batch processing and exception handling

In [ ]:
import logging
from sqlalchemy.exc import SQLAlchemyError, OperationalError

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def fetch_stock_ledger_entry():
    query = text(""" SELECT * FROM `tabStock Ledger Entry` WHERE is_cancelled = 0""")

    try:
        with mysql_engine.connect() as connection:
            results = connection.execution_options(stream_results=True).execute(query)
    
            ## Process the data in chunks
            chunk_size = 10000
    
            chunks = []
    
            while True:
                chunk = results.fetchmany(chunk_size)
    
                if not chunk:
                    break
                chunks.append(pd.DataFrame(chunk, columns = results.keys()))
            
            sle_df =  pd.concat(chunks, ignore_index=True)
            
            run_time = datetime.strftime(datetime.today(), "%Y-%m-%d")
            sle_df.to_parquet(f"data/stock_ledger_entry_{run_time}.parquet")

            return sle_df
            
            
    except OperationalError as e:
        logger.error(f"Database operation error: {e}")
        return None
        
    except SQLAlchemyError as e:
        logger.error(f"SQLAlchemy error: {e}")
        return None

    except Exception as e:
        logger.error(f"Unexected error occured: {e}")
        return None

In [92]:
sle_df = fetch_stock_ledger_entry()

In [99]:
sle_df.shape

(187224, 42)

In [ ]:
query = text(""" SELECT table_name FROM information_schema.tables WHERE table_schema = 'erpnext_db' AND table_name NOT IN  ('__UserSettings','__global_search','__Auth') ORDER BY table_name ASC; """)