In [8]:
import pandas as pd
import numpy as np
import logging

import pymysql
from datetime import datetime

### At first we use the PyMysql engine to extract data and load the data directly to file

First configure mysql / mariadb to accept connections from any IP (dangerous) in /etc/mysq/mariadb.conf.d/50-server.cnf


bind-address = 0.0.0.0

Then create a read-only user and grant SELECT privileges only:

CREATE USER 'etl_user'@'%' IDENTIFIED BY 'mypass980898'; FLUSH PRIVILEGES;

GRANT SELECT ON database_name.* TO 'etl_user'@'%';

In [16]:
connection_config_remote = {
    "host":"169.58.29.108",
    "user":"etl_user",
    "password":"RootRender9090",
    "database":"_8a723ea3d5c7c0d5",
    "port":3306
}

with pymysql.connect(**connection_config_remote) as connection:
    query = """ SELECT 
                    name, 
                    customer, 
                    customer_name, 
                    posting_date, 
                    due_date, 
                    base_grand_total FROM `tabSales Invoice` WHERE docstatus = 1 
                    AND YEAR(posting_date) = 2026 """
    df_remote = pd.read_sql(query, connection)

/tmp/ipykernel_14168/1094148274.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_remote = pd.read_sql(query, connection)

In [17]:
df_remote

,name,customer,customer_name,posting_date,due_date,base_grand_total
0,ACC-SINV-2025-01161,QUICKPACK LIMITED,QUICKPACK LIMITED,2026-05-21,2025-09-21,-3712.0
1,ACC-SINV-2026-00001,Mapacha holdings Limited,Mapacha holdings Limited,2026-01-05,2026-03-06,8816.0
2,ACC-SINV-2026-00002,JAZCO ENTERPRISES,JAZCO ENTERPRISES,2026-01-05,2026-01-06,17748.0
3,ACC-SINV-2026-00003,CHANDARIA INDUSTRIES,CHANDARIA INDUSTRIES,2026-01-06,2026-03-07,85840.0
4,ACC-SINV-2026-00004,Infinity Pack Limited,Infinity Pack Limited,2026-01-06,2026-03-07,54984.0
...,...,...,...,...,...,...
2107,ACC-SINV-2026-02124,WELFAST (K) LTD,WELFAST (K) LTD,2026-08-18,2026-08-19,17052.0
2108,ACC-SINV-2026-02125,NESMAT PACKAGERS LTD,NESMAT PACKAGERS LTD,2026-08-18,2026-10-14,32016.0
2109,ACC-SINV-2026-02126,ALLPACK INDUSTRIES LTD,ALLPACK INDUSTRIES LTD,2026-08-18,2026-11-16,127600.0
2110,ACC-SINV-2026-02127,GN POLYTHENE AND COMPANY LTD(CARTON DIVISION),GN POLYTHENE AND COMPANY LTD(CARTON DIVISION),2026-08-18,2026-10-17,10208.0
2111,ACC-SINV-RET-2026-00001,INKS PRECISION PRINTS LTD,INKS PRECISION PRINTS LTD,2026-06-17,2026-06-17,25755.0

In [3]:
connection_config = {
    "host":"169.58.197.88",
    "user":"root",
    "password":"RootRender90",
    "database":"erpnext_db",
    "port":3306
}

with pymysql.connect(**connection_config) as connection:
    query = """ SELECT 
                    name, 
                    customer, 
                    customer_name, 
                    posting_date, 
                    due_date, 
                    base_grand_total FROM `tabSales Invoice` WHERE docstatus = 1 
                    AND YEAR(posting_date) = 2026"""
    df = pd.read_sql(query, connection)
    today_date = datetime.strftime(datetime.today(),"%Y-%m-%d")
    df.to_parquet(f"data/sales_invoice_{today_date}.parquet")

/tmp/ipykernel_14168/945193918.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection)

### Now we move towards extracting the data using SQLAlchemy

SQLAlchemy helps us manage database connections, create an abstraction layer, handles lazy loading and relationship management.

In [4]:
from sqlalchemy import create_engine, text
from sqlalchemy.pool import QueuePool

In [7]:
## database connection manager / factory to handle connection to a database i.e mysql, oracle, postgresql

## create engine with connection pooling
engine = create_engine(
    "mysql+pymysql://root:RootRender90@localhost/erpnext_db",
    pool_size=10, ## Number of connections to keep in the pool
    max_overflow = 10, ## extra pools to add if pool is exhausted
    pool_pre_ping=True, ## Check connection validity
    echo=False ## do not see SQL logs
)

query = text("""SELECT 
                    name, 
                    customer, 
                    customer_name, 
                    posting_date, 
                    due_date, 
                    base_grand_total FROM `tabSales Invoice` WHERE docstatus = 1 
                    AND YEAR(posting_date) = 2026 """)

with engine.connect() as connection:
    df_a = pd.read_sql(query, connection)

df_a.head(10)

,name,customer,customer_name,posting_date,due_date,base_grand_total
0,ACC-SINV-2026-00001,NMC-00204,MAZIMA BUGAGGA,2026-01-01,2026-01-10,43200.00
1,ACC-SINV-2026-00002,CUST-2025-00119,SPENZA LIMITED,2026-01-01,2026-01-29,114000.00
2,ACC-SINV-2026-00003,NMC-00195,REDLARK GENERAL HOLDINGS LTD,2026-01-01,2025-12-31,55750.00
3,ACC-SINV-2026-00004,CUST-2025-00200,ANDYVAN FREIGHT LOGISTICS,2026-01-01,2026-01-14,40800.00
4,ACC-SINV-2026-00005,NMC-00240,GAJANAN BUILDING SOLUTIONS LIMITED,2026-01-01,2026-03-02,99180.00
5,ACC-SINV-2026-00006,CUST-2025-00078,HU MING INTERNATIONAL FACTORY LTD,2026-01-01,2026-01-02,205548.84
6,ACC-SINV-2026-00007,CUST-2025-00098,MBESHA,2026-01-01,2026-01-12,44000.00
7,ACC-SINV-2026-00008,CUST-2025-00244,SSEMAKULA RICHARD,2026-01-01,2026-01-01,45000.00
8,ACC-SINV-2026-00009,CUST-2025-00200,ANDYVAN FREIGHT LOGISTICS,2026-01-01,2026-01-14,40800.00
9,ACC-SINV-2026-00010,CUST-2025-00200,ANDYVAN FREIGHT LOGISTICS,2026-01-01,2026-01-15,40800.00

In [12]:
df_a.iloc[2:6,1]

2          NMC-00195
3    CUST-2025-00200
4          NMC-00240
5    CUST-2025-00078
Name: customer, dtype: object

In [13]:

mysql_engine = create_engine("mysql+pymysql://root:RootRender90@localhost/erpnext_db",
                           pool_size=10,
                           pool_pre_ping=True,
                           max_overflow=5,
                           echo=False)

def extract_data_from_erp():
    query = text(""" SELECT 
                        name, 
                        supplier, 
                        supplier_name, 
                        posting_date, 
                        due_date, base_grand_total,
                        base_net_total FROM `tabPurchase Invoice` WHERE docstatus = 1 
                        AND is_return = 0 ORDER BY posting_date DESC""")

    with mysql_engine.connect() as connection:
        df = pd.read_sql(query, connection)
    return df

In [14]:
purchases = extract_data_from_erp()

In [15]:
purchases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2319 entries, 0 to 2318
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              2319 non-null   object
 1   supplier          2319 non-null   object
 2   supplier_name     2319 non-null   object
 3   posting_date      2319 non-null   object
 4   due_date          2319 non-null   object
 5   base_grand_total  2319 non-null   float64
 6   base_net_total    2319 non-null   float64
dtypes: float64(2), object(5)
memory usage: 126.9+ KB

In [16]:
### Parametized query to get data using parameters
def get_invoice_by_customer(customer_id):
    query = text("""
                    SELECT si.name,
                           si.customer_name,
                           si.posting_date, 
                           si.due_date,
                           si.payment_terms_template,
                           si.base_grand_total,
                           si.outstanding_amount,
                           si.status
                    FROM `tabSales Invoice` AS si 
                    WHERE si.customer =:customer_id
                    AND si.docstatus = 1
                    ORDER BY si.posting_date DESC
                """)


    ## Context manager 
    with mysql_engine.connect() as connection:
        
        result = connection.execute(query, {"customer_id":customer_id})
        df = pd.DataFrame(result.fetchall(), columns = result.keys())
    return df

In [17]:
res = get_invoice_by_customer("CUST-2025-00254")
res

,name,customer_name,posting_date,due_date,payment_terms_template,base_grand_total,outstanding_amount,status
0,ACC-SINV-2026-04931,KAKUZI,2026-05-19,2026-06-18,,-127500.000000000,0E-9,Return
1,ACC-SINV-2026-04906,KAKUZI,2026-05-18,2026-05-23,30 Days Credit,231800.000000000,231800.000000000,Overdue
2,ACC-SINV-2026-04907,KAKUZI,2026-05-18,2026-06-17,30 Days Credit,91200.000000000,91200.000000000,Unpaid
3,ACC-SINV-2026-04718,KAKUZI,2026-05-12,2026-06-11,30 Days Credit,127500.000000000,0E-9,Credit Note Issued
4,ACC-SINV-2026-04668,KAKUZI,2026-05-11,2026-06-10,30 Days Credit,93000.000000000,93000.000000000,Unpaid
...,...,...,...,...,...,...,...,...
92,ACC-SINV-2025-02087,KAKUZI,2025-09-11,2025-10-09,30 Days Credit,131250.000000000,0E-9,Paid
93,ACC-SINV-2025-02079,KAKUZI,2025-09-10,2025-10-09,30 Days Credit,131250.000000000,0E-9,Paid
94,ACC-SINV-2025-02083,KAKUZI,2025-09-10,2025-10-09,30 Days Credit,127500.000000000,0E-9,Paid
95,ACC-SINV-2025-01878,KAKUZI,2025-09-04,2025-09-30,30 Days Credit,323000.000000000,0E-9,Paid
96,ACC-SINV-2025-02763-1,KAKUZI,2025-08-01,2025-08-31,,3901650.000000000,0E-9,Paid

In [18]:
def individual_sales_report():
    query = text(""" 
                    SELECT 
                        si.name AS invoice_number,
                        si.posting_date,
                        si.customer,
                        si.customer_name,
                        st.sales_person,
                        si.due_date,
                        si.currency,
                        si.payment_terms_template,
                        sii.item_code,
                        sii.item_name, 
                        sii.rate,
                        sii.qty,
                        ROUND(si.base_grand_total,2) AS base_grand_total,
                        ROUND(si.outstanding_amount,2) AS outstanding_amount,
                        si.status
                    FROM `tabSales Invoice Item` AS sii 
                        INNER JOIN `tabSales Invoice` AS si ON sii.parent = si.name
                        LEFT JOIN `tabSales Team` AS st ON si.customer = st.parent
                    WHERE si.docstatus = 1 
                        AND si.is_opening = 0
                        AND si.is_return = 0
                        AND si.status NOT IN ('Credit Note Issued')
                    ORDER BY si.posting_date DESC
                    """)
    with mysql_engine.connect() as connection:
        df = pd.read_sql(query, connection)
        
    if not df.empty:
        ## transformation step
        df['amount_paid'] = df['base_grand_total'] -  df['outstanding_amount']

    return df

In [19]:
item_wise_sales = individual_sales_report()

In [20]:
item_wise_sales.sort_values(by='amount_paid',ascending=False).query("status == 'Paid' ").head(5)

,invoice_number,posting_date,customer,customer_name,sales_person,due_date,currency,payment_terms_template,item_code,item_name,rate,qty,base_grand_total,outstanding_amount,status,amount_paid
11420,ACC-SINV-2025-01415-1,2025-08-01,NMC-00012,CRYSTAL ADHESIVES,Martha Nalonja,2025-10-30,KES,,None,Opening Invoice Item,6078168.0,1.0,6078168.0,0.0,Paid,6078168.0
11419,ACC-SINV-2025-01414-1,2025-08-01,NMC-00012,CRYSTAL ADHESIVES,Martha Nalonja,2025-10-30,KES,,None,Opening Invoice Item,5256134.0,1.0,5256134.0,0.0,Paid,5256134.0
11418,ACC-SINV-2025-01413-1,2025-08-01,NMC-00012,CRYSTAL ADHESIVES,Martha Nalonja,2025-10-30,KES,,None,Opening Invoice Item,4813930.4,1.0,4813930.4,0.0,Paid,4813930.4
11417,ACC-SINV-2025-01412-1,2025-08-01,NMC-00012,CRYSTAL ADHESIVES,Martha Nalonja,2025-10-30,KES,,None,Opening Invoice Item,4385832.4,1.0,4385832.4,0.0,Paid,4385832.4
11548,ACC-SINV-2025-02763-1,2025-08-01,CUST-2025-00254,KAKUZI,Martha Nalonja,2025-08-31,KES,,None,Opening Invoice Item,3901650.0,1.0,3901650.0,0.0,Paid,3901650.0

### Extracting large databases / tables with batch processing and exception handling

In [21]:
import logging
from sqlalchemy.exc import SQLAlchemyError, OperationalError

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def fetch_stock_ledger_entry():
    query = text(""" SELECT * FROM `tabStock Ledger Entry` WHERE is_cancelled = 0 ORDER BY creation DESC""")

    try:
        with mysql_engine.connect() as connection:
            results = connection.execution_options(stream_results=True).execute(query)
    
            ## Process the data in chunks
            chunk_size = 10000
    
            chunks = []
    
            while True:
                chunk = results.fetchmany(chunk_size)
    
                if not chunk:
                    break
                chunks.append(pd.DataFrame(chunk, columns = results.keys()))
            
            sle_df =  pd.concat(chunks, ignore_index=True)

            ## get the query execution time
            run_time = datetime.strftime(datetime.today(), "%Y-%m-%d")
            
            ## Save dataframe to parquet
            sle_df.to_parquet(f"data/stock_ledger_entry_{run_time}.parquet")

            return sle_df
            
            
    except OperationalError as e:
        logger.error(f"Database operation error: {e}")
        return None
        
    except SQLAlchemyError as e:
        logger.error(f"SQLAlchemy error: {e}")
        return None

    except Exception as e:
        logger.error(f"Unexected error occured: {e}")
        return None

In [22]:
sle_df = fetch_stock_ledger_entry()

In [23]:
sle_df.shape

(187224, 42)

In [24]:
query = text(""" SELECT table_name FROM information_schema.tables WHERE table_schema = 'erpnext_db' AND table_name NOT IN  ('__UserSettings','__global_search','__Auth') ORDER BY table_name ASC; """)